apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:54/0Ayxgte9bQJgHM2ADXBhBGEvc5c+lhBeAZrw70FpmoIw26fzqcw==,iv:iImWOuxNebXfPTJUtEUMO/P388siWQWvvWN8pmRhm7U=,tag:qlFWn/qZTMUP15WMf6x3+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3elRoN0lEalRFeEd5dWt2
            ak9kUUhqa0UxaTZDZnRpaU9xd3R5ZmRlYUhvCjRuU2FGTCtWRmRjS0hOTVh2Wkxu
            U05UbGk5WnZnNGhpTTlNQXAyR2h6L2sKLS0tIERHQWxGNVE2RllVMGpha2wwQVht
            WUpIMUdsT3NOL3JQMk5mOHkxZWpFZTQK9LlrSaBlxyGNwkhIdKJ+/X/2GchLbeu6
            67Dvg8xrNVosXQ4qXcBsudIhOfp/kftSQkiUBskuUGQg/995j8aB3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T13:16:17Z"
    mac: ENC[AES256_GCM,data:zAPXComsZQYZBFsPovETxMW2rZFx/3xV8H0zdluoXZnwix3tztNIf9L+R92tvzHPJn9ZhiFtM7oJxYlzbbly2Xx1LyfnTcwzpsIiUVFCpGtD18aELEKhN5jgnipxHin6DKjAqUgAGxOm8bT1RmQu58DgxIAZFLQ69eJHKAAYIkQ=,iv:ykKQHx7dWnibrBprMoygSQ8HC79p3LAxtYNi2ZA4qD0=,tag:qQEIQfVuwk7gzdZATncpLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
