apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5ByWcFgPzBX5lAvUKBN9oJx4zbUR9dleVKOE39apxav4ryvs+ly+PQ==,iv:0qvLW+wTysDlf06mGP4OFGGiX1Lc7xdM22KqejQeQjc=,tag:Zl3T73/qawbmP21eHwZSbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcmZoQmgvU0Z3bkVWbFJt
            eXYzbzcxcm9YNEFlY0Q2MGJFV00ydjk3WFhvCnFKLzBEZ1R1dUl6VWF2R0lWdko4
            WEJiblpZMHRDemZ2cnZRSGpXejlQOEUKLS0tIE1GcHdEYVhmcVJmdmJCcnBSMFZu
            NjZqNS9EbTQ1T2NibGp3djd3emtxaDAKEaz9TDo/2q3RG8RC4URXuqNZ1esg3bbP
            IpBHQcon9sYNJL5oRKxPCtkk7thm1ksTsHfk2uwNI94VBSHmfoENxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T15:21:55Z"
    mac: ENC[AES256_GCM,data:c2H1ICR+ynGU4uBfUhQNnwd3Qv7DQct0mBTVQaf5k05vOB1xsznj83EOSm7GULI50YARKUZbqcRpTMBow8quWT30Xi5yWWfMh9Q/ufiKDDVK7i8S6QgNs/4MABM5DXxJNt8gvDoI7coKvtNFustSPSEHQuxFgPXgHrDtTlfCcL8=,iv:Vp6hcDS51GeiJaPAWAsS0Cj7ry2HNavgL4LWSzumPOU=,tag:TYSF8umrJ8gKXAA9SNvAcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
