apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:IooYWygnglQZv0tkH2swT6sHk8fWiIpypO8rWHKCs3hf1tnnEOZesg==,iv:9I/SgMB3jbpGNbIKKjub7BitNHrDTBXj0HKFx8HTYps=,tag:tpw/FgwJaHhw47xZy6E/Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS002VFMxNDhoQTdyTHBX
            a0pVV25abmh3eDNMaFFxckg5ZmZvRHJCNEdRCmNEa1RBVXBiVEJDbmxweWF5Rm8w
            NGM2Mll2T3UzUXFMZnFLeUxuSFN1WlEKLS0tIExaWStZUEJZWVgrb2JBbnMxSWRR
            Y2x2V0gyRmdjRWwrbVZFUkxSV3JscDAKxgzdWL7dtYK4UO5DLVKNY3rKLLjKXAH+
            mR2uy/9flmWia9JehgRtA1s5PGKH24zFSE42HJnfaOWXQLsxhA59Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T15:02:49Z"
    mac: ENC[AES256_GCM,data:K25qZDTLBY1a7PkJXmbfz3GAipuzw2vXlztZyPFy8dk+uMb7g/JEaud/70l8pmHFm7k6ctTJceRlkAxSsQDXiEeGI1dfaaDzchakNs5v+ZQ9z8gahN6jBJg4GxtThfqsiGD4wDO0Lueh2liFbf4GwKUmN3bIkHKds/FpqqOgsLA=,iv:RlOK3JkSibuSqKJGrwYCpvlHuQHjn0V216EHKEbHxH0=,tag:jFHtIRk9Km2DvBzhbRa8Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
