apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8cs15u3uYXdAOblkFMc=,iv:2ZZ4KMBWPS8wlt9hUytEHoJVpHr29/MsNGdb+b1RIsM=,tag:Z7pAn8ZUzLcnRmLiZmrYRA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0YzdrX76gm2E/ZCplI9jWfYFCOf2tw==,iv:bPiiMCEunmkOsYzZmisJemU7181OSBWtW1j46PH04/o=,tag:NUBeFZrXthzWQedKlYp7XQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:LTUSVzljqx3DCoOxfyBw4ktbknVNCP9R3MmbFtMl9v+/mlDZ,iv:aBNiXTXjMrnlHrDR5b3sTOM0R8yP0fB2oWI///GAAjk=,tag:wtEE3WKyVLHx6LZH6YiDSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUDdUZ3pqUG1UTE5TcDdq
            ZmRkQUROVGd5TDJQZUFwbHJJNmtxazNTaXlvCjBtbEtpa2loVldVVlpmVXkvUzNv
            SU5OZXhYMHB3cnR4L1JUWmd0dWtQcEEKLS0tIDVzazVreURQb2hQSUtCcnlPU0Fj
            bC84Mk04YkxIc1dEOTVEaGlQYWpEUzgKd3gAXrkhWOvDihZ8OvZXRWIgioyzEvV7
            3frX6UVhJ+qg1nAyLs6h+uQFa+cihXVRWQFxlUmfCPLZIn8zuLhnNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T13:39:50Z"
    mac: ENC[AES256_GCM,data:8tQau5HQ/JxdVeuDVuDyqdQuXNZq7nmzEHEDV3GK5zNy4U493q3D+Im89MR2aWhMg9w6QErF4Ck6y4Ckw1UZIT3yEPauYlT8yYVVdGRPwRmSrxWMrn5RVGg1C/J4T9sRqrQz96jEdrH4Spa7J2MUpYv55LaH902xgP6LWq7wfDs=,iv:NPbJV468KGmnmKf7OYHq1xp2PVGyNNwYungCeUy9lLE=,tag:/dzWPMhW+LBXxtA+dqJznw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
