apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Nr7hRUI+B7yx+tE933jYgsijxedUTeapPkzyxUlUnII=,iv:VdNxI/GFl5FRAI01ojhhpfivT2TuHFwOOJV8w/vbR3o=,tag:2R7eeuEq2BNEJ6EtyGVaXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUXZuNmZrYlhqMGdnZTls
            OUpVbUJxaW5LZGgyWWs5TVVBMmd5ejRWVEVFCnQvOFVTVXlCM3hiMUdNZ1pjT1VE
            UG5RUkpiODVvaG16TlplYmIzTDZreEUKLS0tIEhlOTJycFMwVWRzWW9SK254UU5N
            ZTlVZU1zWmV1T052dXJTTXlKK1dLVTQK+9KC3cdhvm2JuOsmm/L107QYsj14nBO/
            JROI+IcutmMLwWkPR+/rYSQKpUPPzHqG5O0TfyVL/Qfv07F9kyMgHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T13:39:50Z"
    mac: ENC[AES256_GCM,data:trFeC/Zdp8OCOfPcBxEqS/kh5JKIDnfwF9/8bbPpNdjOKXqkgtx57ueDxPvp4raw4tdOBvE/d0Y37u0DfACw9/2320Iw+TlqzW0gfS2gWlAAuvHyNYb5vNB4hZchwoF8Szam1rhmoWsiyUAZH8KDefzVGfJ1CwgwiJeMkmgyYDI=,iv:MzSnl5gXsrvWl2Ci0rh8skQ/dM/lpHemGN4pMEnoYBQ=,tag:YdkpOJdOnMM5Roar8N6nTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
