apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Q+1c0T+RpCClUFKmoIVLi0pcIXUymcYWLgcPYUhvlU4XBaM66RGMsQ==,iv:kNDo3tt177hpBAUiAIv9jP8PCjyGE1l/Ph6d4uwgJWs=,tag:rUeFkKhwhjjXPRz/t9b1yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufe3hk4ll5m4x4dnt9297f55csxza8ua9qrpwr5w5kh6kawc3spslh6y8f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZFBxODRpU0pjd1F5a2pF
            NTZWaEFwSmNPNlU4UXlIeVRSUVZ2ZUZFblhrCjIyTWlSY2NyelE1RHV1ckUvM1c1
            bFNzYTVkK2QrYkxTOVZEZjlRUC9Ob2cKLS0tIHlqZlVvNmh1c3VtYXVyMzIvZ2VI
            b3Q1SjhKbTY5OGZpSVBDSzBkVXZnb1kKV3XvQRNkovSAzvQXwgOevkVjLez3CiIx
            ujtf/j2FAT2EaijHOhs/nfbh9YGVC4V6ycmcAShedS4fXQSC8N62DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T13:16:17Z"
    mac: ENC[AES256_GCM,data:SO5KPVAmAtooW1cMrIFPVCTYoF4EbojV3WQsKt9AhFZ3wK3h9F44diJNc7+kyDNl5ayMpzaFYgYQE4NCbmNP0qxzsV/K7RlwIxOxpxgKQHqiunPKEvRnfZkvUcYfW7rC1usbfGT565iylYA219vQc+K/FM7rZn4NTau2rMsvncA=,iv:PpMEHwD0L/0loEuq4Hs/oDwvBEA/b1q6IpZdm/85QVw=,tag:ESdkaVKhWK7aZ74TaVDDBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
